apiVersion: batch/v1
kind: Job
metadata:
  name: just-test # Your training job name
  
spec:
  backoffLimit: 0   # add this line so --> If your pod failed, the training job will stop.
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: gitlab-docker-secret
      volumes:
        - name: shared-memory # This is to resolve the dataloader OOM issue.
          emptyDir:
            medium: Memory
        - name: dataset-volume
          persistentVolumeClaim:
            claimName: zero      # <------- your PVC name    kubectl get pvc

      containers:
        - name: zero-container # It is recommended to name your container according to the project
          image: docker.aiml.team/jian.zhou/mimicgen:latest # You can reuse this image for different projects if their python dependencies are the same.
          imagePullPolicy: Always
          stdin: true
          tty: true
          command: ["/bin/bash", "-c"]
          args: 
              - |
                apt install -y libegl1-mesa  libegl1-mesa-dev libgles2-mesa  libgl1-mesa-glx libgl1-mesa-dev libx11-dev 
                source /root/miniforge3/etc/profile.d/conda.sh    # load the conda functions
                conda activate equidiff
                which python
                export HYDRA_FULL_ERROR=1
                cd /data/first
                git pull
                pip install -e .
                python train.py --config-name=train_diffusion_unet task_name=stack_d1 n_demo=100 \
                +env_runner.n_envs=5 +env_runner.n_test=3 +env_runner.n_train=2 \





          resources:
            limits:
              cpu: 8
              nvidia.com/gpu: 1          # <------- If you don't need any of GPUs, Please comment-out this line.
              memory: 60Gi
            requests:
              cpu: 8
              nvidia.com/gpu: 1          # <------- If you don't need any of GPUs, Please comment-out this line.
              memory: 60Gi
          
            


          volumeMounts:
            - name: dataset-volume
              mountPath: /data
            - name: shared-memory
              mountPath: /dev/shm
          env:
            - name: GITLAB_TOKEN
              valueFrom:
                secretKeyRef:
                    name: gitlab-token  # kubectl get secrets
                    key:  access-token