name: mimicgen_abs

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    states:
      shape: [45]
  action: 
    shape: [8]

shape_meta_env: &shape_meta_env
  # acceptable types: rgb, low_dim
  obs:
    agentview_image:
      shape: [3, 84, 84]
      type: rgb

    states:
      shape: [45]

  action: 
    shape: [8]


abs_action: &abs_action True

env_runner:
  _target_: equi_diffpo.env_runner.robomimic_image_runner_tmp.RobomimicImageRunner
  dataset_path: ${dataset_path}
  shape_meta: *shape_meta_env
  n_train: 6
  n_train_vis: 2
  train_start_idx: 0
  n_test: 50
  n_test_vis: 4
  test_start_seed: 100000
  max_steps: ${get_max_steps:${task_name}}
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  render_obs_key: 'agentview_image'
  fps: 10
  crf: 22
  past_action: ${past_action_visible}
  abs_action: *abs_action
  tqdm_interval_sec: 1.0
  n_envs: 28

dataset:
  # _target_: equi_diffpo.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
  _target_: ${dataset}
  n_demo: ${n_demo}
  shape_meta: *shape_meta
  dataset_path: ${dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  abs_action: *abs_action
  use_legacy_normalizer: False
  use_cache: 1
  seed: 42
  val_ratio: 0.02
